backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/img/netlify-uploads" # Media files will be stored in the repo under assets/img/uploads
collections:
- name: "pages"
  label: "Pages"
  label_singular: "Page"
  files:
  - name: "people"
    label: "People Page"
    file: "_data/pages/people.yml"
    extension: yml
    format: yml
    fields:
    - name: "people_list"
      label: "People List"
      widget: "list"
      fields:
      - {name: "name", label: "Name", widget: "string"}
      - {name: "category", label: "Category", widget: "string"}
      - {name: "email", label: "Email", widget: "string"}
      - {name: "photo", label: "Photo", widget: "image"}
  - name: "research"
    label: "Research Page"
    file: "_data/pages/research.yml"
    extension: yml
    format: yml
    fields:
    - {name: "about_language_and_space", label: "About Language and Space", widget: "string"}
    - {name: "about_event_representation", label: "About Event Representation", widget: "string"}
    - {name: "about_neuroaesthetics", label: "About Neuroaesthetics", widget: "string"}
    - {name: "about_neuroethics", label: "About Neuroethics", widget: "string"}
    - {name: "about_miscellaneous", label: "About Miscellaneous", widget: "string"}
    - name: "publications_list"
      label: "Publications List"
      widget: "list"
      fields:
      - {name: "title", label: "Title", widget: "string"}
      - {name: "authors", label: "Authors", widget: "string"}
  - name: "news"
    label: "News Page"
    file: "_data/pages/news.yml"
    extension: yml
    format: yml
    fields:
    - name: "news_list"
      label: "News List"
      widget: "list"
      fields:
      - {name: "title", label: "Title", widget: "string"}
      - {name: "source", label: "Source", widget: "string"}
- name: "publications" # Used in routes, e.g., /admin/collections/blog
  label: "Publications" # Used in the UI
  label_singular: "Publication" # Used in the UI
  folder: "_publications" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  extension: html
  format: yaml-frontmatter
  fields: # The fields for each document, usually in front matter
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Authors", name: "authors", widget: "string"}
