backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/img/uploads" # Media files will be stored in the repo under assets/img/uploads
collections:
  - name: "publications" # Used in routes, e.g., /admin/collections/blog
    label: "Publications" # Used in the UI
    label_singular: "Publication" # Used in the UI
    folder: "_publications" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: html
    format: yaml-frontmatter
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Authors", name: "authors", widget: "string"}
